### ISSUE TITLE
Integration with ArgoCD don't work with https downloader plugin

### ISSUE THREAD

**Issue by krzwiatrzyk** [jkroepke/helm-secrets#212]
### Current Behavior

I am trying to install this Pihole Application on my cluster, with values from git repository and age key from cluster secret: https://github.com/krzwiatrzyk/local-cluster/blob/main/clusters/firefly/argo-apps/templates/homelab/002-pihole-app.yaml

My ArgoCD values.yaml (based on [docs](https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration)): https://github.com/krzwiatrzyk/local-cluster/blob/main/clusters/firefly/argocd-values.yaml

Values file is downloadable and secret with age key is on the cluster, for testing it locally i have used command:
```
task: [template-with-cluster-secret] helm template . -f secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#key.asc?https://raw.githubusercontent.com/krzwiatrzyk/local-cluster/main/clusters/firefly/test/test-chart/values-unencrypted.yaml
---
# Source: argo-apps/templates/test.yaml
hostIP: 192.168.43.170
password: from-git
```
and as you can see, it works.

Error (I am unable to :
```
rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template pihole --namespace homelab --kube-version 1.22 --values secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#key.asc?https://raw.githubusercontent.com/krzwiatrzyk/local-cluster/main/clusters/firefly/argo-apps/values/pihole.yaml --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1/MutatingWebhookConfiguration --api-versions admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1/CustomResourceDefinition --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1/APIService --api-versions apps/v1 --api-versions apps/v1/ControllerRevision --api-versions apps/v1/DaemonSet --api-versions apps/v1/Deployment --api-versions apps/v1/ReplicaSet --api-versions apps/v1/StatefulSet --api-versions argoproj.io/v1alpha1 --api-versions argoproj.io/v1alpha1/AppProject --api-versions argoproj.io/v1alpha1/Application --api-versions argoproj.io/v1alpha1/ApplicationSet --api-versions argoproj.io/v1alpha1/ArgoCDExtension --api-versions autoscaling/v1 --api-versions autoscaling/v1/HorizontalPodAutoscaler --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta1/HorizontalPodAutoscaler --api-versions autoscaling/v2beta2 --api-versions autoscaling/v2beta2/HorizontalPodAutoscaler --api-versions batch/v1 --api-versions batch/v1/CronJob --api-versions batch/v1/Job --api-versions batch/v1beta1 --api-versions batch/v1beta1/CronJob --api-versions bitnami.com/v1alpha1 --api-versions bitnami.com/v1alpha1/SealedSecret --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1/CertificateSigningRequest --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1/Lease --api-versions discovery.k8s.io/v1 --api-versions discovery.k8s.io/v1/EndpointSlice --api-versions discovery.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1/EndpointSlice --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1/Event --api-versions events.k8s.io/v1beta1 --api-versions events.k8s.io/v1beta1/Event --api-versions flowcontrol.apiserver.k8s.io/v1beta1 --api-versions flowcontrol.apiserver.k8s.io/v1beta1/FlowSchema --api-versions flowcontrol.apiserver.k8s.io/v1beta1/PriorityLevelConfiguration --api-versions helm.cattle.io/v1 --api-versions helm.cattle.io/v1/HelmChart --api-versions helm.cattle.io/v1/HelmChartConfig --api-versions k3s.cattle.io/v1 --api-versions k3s.cattle.io/v1/Addon --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1/Ingress --api-versions networking.k8s.io/v1/IngressClass --api-versions networking.k8s.io/v1/NetworkPolicy --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1/RuntimeClass --api-versions node.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1/RuntimeClass --api-versions policy/v1 --api-versions policy/v1/PodDisruptionBudget --api-versions policy/v1beta1 --api-versions policy/v1beta1/PodDisruptionBudget --api-versions policy/v1beta1/PodSecurityPolicy --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1/ClusterRole --api-versions rbac.authorization.k8s.io/v1/ClusterRoleBinding --api-versions rbac.authorization.k8s.io/v1/Role --api-versions rbac.authorization.k8s.io/v1/RoleBinding --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1/PriorityClass --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1/CSIDriver --api-versions storage.k8s.io/v1/CSINode --api-versions storage.k8s.io/v1/StorageClass --api-versions storage.k8s.io/v1/VolumeAttachment --api-versions storage.k8s.io/v1beta1 --api-versions storage.k8s.io/v1beta1/CSIStorageCapacity --api-versions traefik.containo.us/v1alpha1 --api-versions traefik.containo.us/v1alpha1/IngressRoute --api-versions traefik.containo.us/v1alpha1/IngressRouteTCP --api-versions traefik.containo.us/v1alpha1/IngressRouteUDP --api-versions traefik.containo.us/v1alpha1/Middleware --api-versions traefik.containo.us/v1alpha1/MiddlewareTCP --api-versions traefik.containo.us/v1alpha1/ServersTransport --api-versions traefik.containo.us/v1alpha1/TLSOption --api-versions traefik.containo.us/v1alpha1/TLSStore --api-versions traefik.containo.us/v1alpha1/TraefikService --api-versions v1 --api-versions v1/ConfigMap --api-versions v1/Endpoints --api-versions v1/Event --api-versions v1/LimitRange --api-versions v1/Namespace --api-versions v1/Node --api-versions v1/PersistentVolume --api-versions v1/PersistentVolumeClaim --api-versions v1/Pod --api-versions v1/PodTemplate --api-versions v1/ReplicationController --api-versions v1/ResourceQuota --api-versions v1/Secret --api-versions v1/Service --api-versions v1/ServiceAccount --include-crds` failed exit status 2: panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1813b98] goroutine 1 [running]: bytes.(*Buffer).Bytes(...) bytes/buffer.go:54 helm.sh/helm/v3/pkg/cli/values.readFile({0xc000188240, 0x100000000000007}, {0xc0003bb780, 0x3, 0x4}) helm.sh/helm/v3/pkg/cli/values/options.go:120 +0x138 helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc00007fc80, {0xc0003bb780, 0xc0006b59f8, 0xc0004bdd40}) helm.sh/helm/v3/pkg/cli/values/options.go:48 +0x385 main.runInstall({0xc00066a000, 0x2c, 0xc0006b5ac0}, 0xc0005489a0, 0x2000, {0x1f67d00, 0xc000134008}) helm.sh/helm/v3/cmd/helm/install.go:198 +0x385 main.newTemplateCmd.func2(0xc00039f900, {0xc00066a000, 0x1, 0xda}) helm.sh/helm/v3/cmd/helm/template.go:82 +0x22a github.com/spf13/cobra.(*Command).execute(0xc00039f900, {0xc00056d000, 0xda, 0x100}) github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e github.com/spf13/cobra.(*Command).ExecuteC(0xc0002db680) github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc github.com/spf13/cobra.(*Command).Execute(...) github.com/spf13/cobra@v1.3.0/command.go:902 main.main() helm.sh/helm/v3/cmd/helm/helm.go:83 +0x234
```

### Expected Behavior

Correct installation of the application.

### Steps To Reproduce

```markdown
Install ArgoCD with values provided in the bug description.
```

### Environment

- Helm Version: 3.8.0 (in ArgoCD server)
- Helm Secrets Version: 3.13.0 and 3.12.0
- OS: Ubuntu 22.04
- Shell: zsh
- ArgoCD version: v2.3.3

**Comment by krzwiatrzyk** [comment]
Running command in `repoServer` for showing values from the url results with following error: 
```
argocd@argocd-repo-server-9f49b94d4-gwvxq:~$ helm secrets view https://raw.githubusercontent.com/krzwiatrzyk/local-cluster/main/clusters/firefly/test/test-chart/values-unencrypted.yaml
Error: plugin "secrets" exited with error
```

while on the host:
```
helm secrets view https://raw.githubusercontent.com/krzwiatrzyk/local-cluster/main/clusters/firefly/test/test-chart/values-unencrypted.yaml
password: from-git
```

**Comment by krzwiatrzyk** [comment]
Screenshots of the error for better readability: 
![image](https://user-images.githubusercontent.com/52850037/163796241-e29b3eb5-7ce0-4f87-9c23-92a3772067b0.png)
![image](https://user-images.githubusercontent.com/52850037/163796258-86945043-63d9-4e3a-b853-1374b26b2035.png)

**Comment by jkroepke** [comment]
The go panic runtime error is a follow up error from helm https://github.com/helm/helm/issues/10685

Are you able to curl your values, like

```
curl https://raw.githubusercontent.com/krzwiatrzyk/local-cluster/main/clusters/firefly/test/test-chart/values-unencrypted.yaml
```

**Comment by krzwiatrzyk** [comment]
Right now it is not possible to run `curl`/`wget` as they are not installed in repo-server container. I will try later with ephemeral containers or to install in inside:
```
argocd@argocd-repo-server-75f8fbd787-xp4nn:~$ curl
bash: curl: command not found
argocd@argocd-repo-server-75f8fbd787-xp4nn:~$ wget
bash: wget: command not found
```
I tried to copy `curl` into the pod but privileges are blocking me:
```
argocd@argocd-repo-server-75f8fbd787-xp4nn:/tmp$ ./curl
bash: ./curl: Permission denied
```

But FYI, I am able to download that file from within the cluster:
```
❯ kubectl run --rm -it busybox --image nicolaka/netshoot -- sh
If you don't see a command prompt, try pressing enter.
~ # curl https://raw.githubusercontent.com/krzwiatrzyk/local-cluster/main/clusters/firefly/test/test-chart/values
-unencrypted.yaml && echo
password: from-git
```

**Comment by jkroepke** [comment]
> bash: ./curl: Permission denied

you had you run `chmod +x` to add the executable flag on that binary.

Anyway, helm-secrets have a dependency agist curl/wget. 

https://github.com/jkroepke/helm-secrets/blob/480331a57eae2458463b7420edbf54bc17abc90e/scripts/lib/http.sh#L5-L15

**Comment by jkroepke** [comment]
Hi,

in #213, I updated already the README.md including support for curl binaries on custom locations, adjust the PATH isn't needed.

Take a look at https://github.com/jkroepke/helm-secrets/blob/fe48b7786a4a24a174a5bec9fb00a5d21b687f9b/docs/ArgoCD%20Integration.md#option-2-init-container to check if the works for you.

**Comment by krzwiatrzyk** [comment]
I have tried to run it with code from that PR but still it has resulted with error. However, now error description is more explanatory:

```
Error from server (NotFound): secrets "helm-secrets-private-keys" not found [helm-secrets] Couldn't get kubernetes secret argocd/helm-secrets-private-keys panic: runtime error: invalid memory address or nil pointer dereference 
```

I have checked and both secret exists and service account for `repo-server` can access it:
```
❯ kubectl auth can-i get secret/helm-secrets-private-keys -n argocd --as system:serviceaccount:argocd:argocd-repo-server
yes
```

```
❯ kubectl get secrets -n argocd helm-secrets-private-keys
NAME                        TYPE     DATA   AGE
helm-secrets-private-keys   Opaque   1      19m
```

I have installed `helm-secrets` plugin from PR with following spec:
```
 wget https://github.com/jkroepke/helm-secrets/tarball/error-handling-download -qO- | tar -C /custom-tools/helm-plugins -xz;
 mv /custom-tools/helm-plugins/jkroepke-helm-secrets-212447b /custom-tools/helm-plugins/helm-secrets
```

and ofc variables and downloading for `curl` are set according to docs.

In the pod there is a `Dockerfile` in the plugin dir (which you added in this PR so I assume it is correct):
```
argocd@argocd-repo-server-848fb55b94-vgpm4:~$ cd /custom-tools/helm-plugins/helm-secrets/
argocd@argocd-repo-server-848fb55b94-vgpm4:/custom-tools/helm-plugins/helm-secrets$ ls
CHANGELOG.md	    CONTRIBUTING.md  LICENSE	TODO.md		      codecov.yml      contrib	examples		       plugin.yaml  tests
CODE_OF_CONDUCT.md  Dockerfile	     README.md	artifacthub-repo.yml  completion.yaml  docs	jkroepke-helm-secrets-212447b  scripts
```



Entire stack trace:
```
Error from server (NotFound): secrets "helm-secrets-private-keys" not found [helm-secrets] Couldn't get kubernetes secret argocd/helm-secrets-private-keys panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1813b98] goroutine 1 [running]: bytes.(*Buffer).Bytes(...) bytes/buffer.go:54 helm.sh/helm/v3/pkg/cli/values.readFile({0xc00010a540, 0x100000000000007}, {0xc0003b9c00, 0x3, 0x4}) helm.sh/helm/v3/pkg/cli/values/options.go:120 +0x138 helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc0002dbf80, {0xc0003b9c00, 0xc00081f9f8, 0xc00044cda0}) helm.sh/helm/v3/pkg/cli/values/options.go:48 +0x385 main.runInstall({0xc0002d5300, 0x4a1ac6, 0xc00081fa88}, 0xc000106840, 0xc000182f30, {0x1f67d00, 0xc00000e018}) helm.sh/helm/v3/cmd/helm/install.go:198 +0x385 main.newTemplateCmd.func2(0xc000448500, {0xc0002d5300, 0x1, 0x10a}) helm.sh/helm/v3/cmd/helm/template.go:82 +0x22a github.com/spf13/cobra.(*Command).execute(0xc000448500, {0xc0002d4000, 0x10a, 0x130}) github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e github.com/spf13/cobra.(*Command).ExecuteC(0xc00068fb80) github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc github.com/spf13/cobra.(*Command).Execute(...) github.com/spf13/cobra@v1.3.0/command.go:902 main.main() helm.sh/helm/v3/cmd/helm/helm.go:83 +0x234
```

**Comment by krzwiatrzyk** [comment]
![obraz](https://user-images.githubusercontent.com/52850037/164170495-b32a7eac-2bd6-4f84-9d16-81daa29cbb81.png)

**Comment by krzwiatrzyk** [comment]
Kubernetes version (in case it is relevant):
```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7+k3s1", GitCommit:"ac70570999c566ac3507d2cc17369bb0629c1cc0", GitTreeState:"clean", BuildDate:"2021-11-29T16:40:13Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by krzwiatrzyk** [comment]
I have checked and `kubectl` binary from `repo-server` is able to access that secret as well:
```
argocd@argocd-repo-server-86894f74d6-hk5wc:/custom-tools$ ./kubectl get secret -n argocd helm-secrets-private-keys
NAME                        TYPE     DATA   AGE
helm-secrets-private-keys   Opaque   1      82m
```

I have found that code responsible for obtaining secret is here: 
https://github.com/jkroepke/helm-secrets/blob/main/scripts/commands/downloader.sh#L161-L163

**Comment by jkroepke** [comment]
Does

```

**Comment by krzwiatrzyk** [comment]
Thanks for explanation, I will try again later today with fresh ArgoCD installation.
